name: whisper_cpp_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Note: Updated to a more modern SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # For iOS style icons.
  cupertino_icons: ^1.0.8

  # For finding commonly used locations on thefilesystem.
  path_provider: ^2.1.3 # Note: Updated to the latest version

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # flutter_overlay_window: ^0.4.4

  # For audio recording
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.1

  ffmpeg_kit_flutter_new: ^3.2.0
  ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices.
  flutter_lints: ^4.0.0 # Note: Updated to the latest version

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ggml-tiny.en.bin
    - assets/test.wav